### ISSUE TITLE
[Feature Request] Disable automatic updates option in the config

### ISSUE THREAD

**Issue by Sootie1776** [V1nc3ntWasTaken/NoEncryption#12]
Hi, I run a production server but I'm currently hesitant to use your plugin because it has an automatic update feature, while in practice it's good intentions can do harm for various reasons. It's [generally accepted](https://www.spigotmc.org/threads/plugin-authors-should-not-be-allowed-to-automatically-download-jars-to-update-itself.444889/) if you have automatic updates it ships disabled, or at very least with a option to disable.

Please add a configuration option to disable this that you check before downloading a newer version, version checking and reminding should be OK to tell OPs about new versions etc.

**Comment by V1nc3ntWasTaken** [comment]
Don't mean this the way it may seem, but the auto updating part of it only activates if you install an incompatible version. Ex. You have MC 1.19.1 and you download NoEncryption 3.1 for 1.19.2. It will detect this and try installing the version you had, version 3.1 but for 1.19.1, and it will attempt to delete the NoEncryption 1.19.1 jar if the download was successful, upon the plugin being disabled. (So as long as you use the proper jar for your server, it shouldn't make any connections to a third party, or attempt to delete or modify any files.)

Although I should be able to implement a manual download through running a command if the plugin detects as incompatible. (And possibly an update notifier, and automatic/manual updating modules)
