### ISSUE TITLE
Latest Essentials error relation

### ISSUE THREAD

**Issue by semazurek** [V1nc3ntWasTaken/NoEncryption#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues and have not found a duplicate relating to my issue.

### Are you using the latest version of NoEncryption (Must be using V1nc3ntWasTaken's fork)?

- [X] I am using the latest version of NoEncryption compatible with my server version.

### NoEncryption Version

4.2

### Minecraft Version

1.19.2

### Server Type

PaperMC 1.19.2-135 latest always updated with latest stable build EssentialX main + EssentialsX Chat

### Describe the bug

Server at startup always show this log:
[23:16:24] [Server thread/WARN]: [Essentials] Loaded class {0} from {1} which is not a depend or softdepend of this plugin.
[23:16:24] [Server thread/ERROR]: [Essentials] You use plugins that are having problems with EssentialsX and others.
[23:16:24] [Server thread/INFO]: [Essentials] Class that determines the status: me.doclic.noencryption.NoEncryption

Plugin itself works fine but I noticed that after long time of runnig server occur logs of crash dump and ticks server not responding +10sec and may it be becouse of that plugin or connection essential + plugin not sure.

### Reproducible Test

I've used:
　- ClearLag 3.2.2
　- SkinsRestorer 14.2.3
　- NoEncryption 4.2
　- Essentials 2.19.7
　- EssentialsChat 2.19.7

**Comment by V1nc3ntWasTaken** [comment]
So, Essentials put NoEncryption into their broken plugins list inside the EssentialsX plugin itself, so in reality, EssentialsX is loading a class from NoEncryption

`NoEncryption` as `NoEncryption`
![image_2022-09-17_194138074](https://user-images.githubusercontent.com/79623093/190880797-e99737fa-5021-416a-8c73-44247f53acfd.png)

`NoEncryption` not as `NoEncryption`
![image](https://user-images.githubusercontent.com/79623093/190881175-eccbf7ea-3722-4b6f-ba1c-be8a18aacdce.png)

(I changed the package from `me.doclic.noencryption` to `me.v1nc3ntwastaken.noencryption`, and it no longer displays the errors/warnings)

What I found when I was researching: 

Update VersionUtil and /ess version [EssentialsX/Essentials #5036](https://github.com/EssentialsX/Essentials/pull/5036)
[Changes to Essentials/src/main/java/com/earth2me/essentials/utils/VersionUtil.java](https://github.com/EssentialsX/Essentials/commit/a39476067767947802948c81f8f96c15ca252186#diff-b22e2c133f5b562c453ed95c7082951d0be1739eb278d267cce1b7a0724ca966)

I will attempt to fix whatever bugs my fork may have, and contact the Essentials team and ask them to whitelist our plugin, but currently, this is out of my control. Although, I will keep this open, just on the back burner.

**Comment by semazurek** [comment]
Still the same error/warning with essentialsx + noencryption 4.3

Console log:
[01:16:29] [Server thread/INFO]: [Essentials] Enabling Essentials v2.19.7
[01:16:29] [Server thread/WARN]: [Essentials] Loaded class {0} from {1} which is not a depend or softdepend of this plugin.
[01:16:29] [Server thread/ERROR]: [Essentials] You are running plugins that cause serious problems with EssentialsX and other plugins.
[01:16:29] [Server thread/INFO]: [Essentials] Class that determines the status: me.doclic.noencryption.NoEncryption

Let's wait for new update from essentials team 😒
