### ISSUE TITLE
Update to 1.19.3 

### ISSUE THREAD

**Issue by xGinko** [V1nc3ntWasTaken/NoEncryption#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues and have not found a duplicate relating to my issue.

### Are you using the latest version of NoEncryption (Must be using V1nc3ntWasTaken's fork)?

- [X] I am using the latest version of NoEncryption compatible with my server version.

### NoEncryption Version

Other (Please specify in Server Type)

### Minecraft Version

Other (Please specify in Server Type)

### Server Type

Purpur 1.19.3 build 1900, NoEncryption v4.3 for 1.19.2

### Describe the bug

Feature to disable the warning message about unsigned chat is not working anymore on 1.19.3, also the plugin warns you about incompatibility. 

Chat reporting is still not possible though and the red (!) are also still hidden, so this is most likely just a minor incompatibility.

### Reproducible Test

Run NoEncryption v4.3 on any 1.19.3 paper or paper type server

**Comment by simsnet** [comment]
A lot of popular plugins and mods for 1.19.3 have been slightly delayed for some reason.  OptiFine 1.19.3 dev builds just got released a few days ago.

**Comment by xGinko** [comment]
I don't follow mojangs updates as eagerly as I used to, could it be because 1.19.4 is around the corner?

I mean as I stated, everything still works except for the config option to hide the warning message, so this post is just here to report it

**Comment by EagL3-GIT** [comment]
Any news?

**Comment by simsnet** [comment]
@EagL3-GIT @xGinko V1nc3nt has moved to Doclic's repo here: [Doclic/NoEncryption](https://github.com/Doclic/NoEncryption/releases)

**Comment by V1nc3ntWasTaken** [comment]
^

**Comment by xGinko** [comment]
Im so slow, thanks guys!
