### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "String.length()

### ISSUE THREAD

**Issue by Kyrobi** [V1nc3ntWasTaken/NoEncryption#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues and have not found a duplicate relating to my issue.

### Are you using the latest version of NoEncryption (Must be using V1nc3ntWasTaken's fork)?

- [X] I am using the latest version of NoEncryption.

### NoEncryption Version

3.0

### Minecraft Version

1.19.1

### Server Type

PufferFish 1.19.2

### Describe the bug

I came here to download the fork for NoEncrryption because the original one would kick players when they type a message.
However, a new error has occurred. When a player joins, they are immediately kicked from the server with the message

NightShadow0901 lost connection: Internal Exception: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null

### Reproducible Test

I join the server with version 3.1 of the plugin for 1.19.2 and immediately get kicked

**Comment by Dogocoton** [comment]
Minecraft Version: 1.19.1
Server Type: PufferFish 1.19.2

Here is your problem

**Comment by NoaHimesaka1873** [comment]
I also have exactly the same issue but only when I use some commands (e.g. /about)
Tested with Pufferfish 1.19.2, Minecrarft 1.19.2

https://user-images.githubusercontent.com/39993457/183402880-7f71194c-79eb-4eac-bf93-7a4f9dd10737.mov

**Comment by V1nc3ntWasTaken** [comment]
The latest release [Release 3.2](https://github.com/V1nc3ntWasTaken/NoEncryption/releases/tag/3.2) should patch this bug, and close this issue. If you have any other issues or bugs, please create a new issue. Thank you for reporting this!
